In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Elementos vectoriales
Escalar = "una variable cualquiera con cualquier tipo de dato"
#matriz, arrays unidos
#tensor, matrices unidas

In [12]:
Vector1 = np.array([1,4,7])
Vector2 = np.array([3,5,2])
Vector3 = np.array([3,6,3])
Matriz = (Vector1,Vector2,Vector3)
Matriz = np.array(Matriz)
print(Matriz)

[[1 4 7]
 [3 5 2]
 [3 6 3]]


In [13]:
#dimension
print(Vector1.size)


3


In [14]:
#Operaciones vectoriales y matriciales + matrices especiales
#Trasposicion
V1T = Vector1.T
print(V1T)
#Op basicas, mismos signos que con solo escalares
#Producto Punto
V1ppV2 = np.dot(Vector1,Vector2)
print(V1ppV2)
pdot2 = Vector1.dot(Vector2)
print(pdot2)
#Producto Cruz
V1pcV2 = np.cross(Vector1,Vector2)
print(V1pcV2)
#Matriz Inversa
MInv = np.linalg.inv(Matriz)
print(MInv)
#determinante
Det = np.linalg.det(Matriz)
print(Det)
#Traza
Traza = np.trace(Matriz)
print(Traza)
#Matriz unos
Zr = np.ones(3)
print(Zr)
#Matriz identidad
Id = np.identity(3)
print(Id)
#Cualquier otra, buscar en la libreria de algebra lineal

[1 4 7]
37
37
[-27  19  -7]
[[ 0.25        2.5        -2.25      ]
 [-0.25       -1.5         1.58333333]
 [ 0.25        0.5        -0.58333333]]
11.999999999999995
9
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Vectores
#Norma
Norma = np.linalg.norm(Vector1)
print(Norma)

8.12403840463596
