In [2]:
import numpy as np
#numpy y arrays, uso basico
lista = [1,4,54,2,6,56,234,54,423,0,54]
print(lista)
Arr = np.array(lista, dtype = 'float64')#define otro tipo de dato
print(Arr)
print(type(Arr))
matriz = [[1,8,7],[8,24,5],[7,7,8]]
matriz = np.array(matriz)


 #metodos de arrays
print(Arr[0])
ordenado = list(range(0,12))
print(ordenado)
orden2 = np.arange(0,120,5)
print("Desoues va el arange")
print(orden2)#igual que el range pero ya directamente como el array
unitos = np.ones((5,5))#un array de ceros XD,#tambien con ones
print(unitos)
#crea un array de n numeros en un intervalo
interxd = np.linspace(0,134,31)
print(interxd)
Matrizdiagonal = np.eye(4)
print(Matrizdiagonal)
val = np.random.rand()
print(val)#genera un numero random de 0 a 1, se multiplica para obtener lo deseado
matrand = np.random.randint(1,100,(6,6)) #no existe randfloat
print(matrand)

[1, 4, 54, 2, 6, 56, 234, 54, 423, 0, 54]
[  1.   4.  54.   2.   6.  56. 234.  54. 423.   0.  54.]
<class 'numpy.ndarray'>
1.0
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Desoues va el arange
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[  0.           4.46666667   8.93333333  13.4         17.86666667
  22.33333333  26.8         31.26666667  35.73333333  40.2
  44.66666667  49.13333333  53.6         58.06666667  62.53333333
  67.          71.46666667  75.93333333  80.4         84.86666667
  89.33333333  93.8         98.26666667 102.73333333 107.2
 111.66666667 116.13333333 120.6        125.06666667 129.53333333
 134.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
0.8252478990547376
[[91 76 58 48 24 42]
 [10 19  6 14 73 10]
 [89 31 37 40 59 81]
 [76 39 97 94  5 46]
 [23  9 34  4 58 69]
 [12 54 95 66 42 53]]


In [9]:
#tipos de datos
#los arrrays manejan un unico tipo
print(Arr.dtype)
Arr = Arr.astype(np.int64)#cambia el tipo de dato
print(Arr.dtype)
#hay los ya mencionados, bool_ (en bool cualquier numero es 1), string_

float64
int64


In [10]:
#Dimension
print(Arr.ndim)
print(matriz.ndim)
#agrega
Arr = np.expand_dims(Arr,axis=0)
print(Arr.ndim,Arr)
Arr = np.squeeze(Arr)
print(Arr.ndim)

1
2
2 [[  1   4  54   2   6  56 234  54 423   0  54]]
1


In [11]:
#shape y reshape
#shape: indica las filas y columnas del arreglo o matriz
#reshape: cambia la forma, cambia el nxm
Matz = np.random.randint(1,15,(14,4))
print(Matz.shape)
#print(Matz)
Matz = Matz.reshape(7,8)#tiene que tener el mismo numero de elementos
print(Matz)

(14, 4)
[[ 8  2  1  1 10 12 11  6]
 [ 9  1  8 11  3  9  5  1]
 [ 9  4  2 14  2  9 11  3]
 [10  6 11  5 13  7  6  8]
 [ 2  8  1  5  6  3  6 14]
 [10 11  7 10  8  2  9  3]
 [14 11  8  1  3  9 10  7]]


In [12]:
maxmatz = Matz.max(0)#valor mas grande, 0 eje y, 1 eje x
print(maxmatz)
print(Matz.argmax(0))#indica la posicion del mayor
#igual para minimos
rangoestadistico = Matz.ptp()
print(rangoestadistico)#tambien se puede por ejes

print(np.percentile(Matz,25))
print(np.median(Matz))
print(np.std(Matz))#saca la desvest
print(np.var(Matz))#varianza
#mean es promedio


[14 11 11 14 13 12 11 14]
[6 5 3 2 3 0 0 4]
13
3.0
7.5
3.8390780674744382
14.738520408163266


In [13]:
Copiamatz = Matz.copy()
print(Copiamatz)

[[ 8  2  1  1 10 12 11  6]
 [ 9  1  8 11  3  9  5  1]
 [ 9  4  2 14  2  9 11  3]
 [10  6 11  5 13  7  6  8]
 [ 2  8  1  5  6  3  6 14]
 [10 11  7 10  8  2  9  3]
 [14 11  8  1  3  9 10  7]]


In [14]:
#operaciones
#es recomendable multiplicar
mult = Matz*2
print(mult)
#si la operacion da una indeterminacion bota inf y lo demas lo realiza

#producto punto
Mat1 = matriz -5*2
print(Mat1)
print(matriz)
Prodpunto= np.matmul(matriz,Mat1)
print(Prodpunto)
Prodpunto2 = matriz @ Mat1.T #T es transpuesta
print(Prodpunto2)

#producto cruz
ProdCruz = np.cross(matriz, Mat1)
print(ProdCruz)

[[16  4  2  2 20 24 22 12]
 [18  2 16 22  6 18 10  2]
 [18  8  4 28  4 18 22  6]
 [20 12 22 10 26 14 12 16]
 [ 4 16  2 10 12  6 12 28]
 [20 22 14 20 16  4 18  6]
 [28 22 16  2  6 18 20 14]]
[[-9 -2 -3]
 [-2 14 -5]
 [-3 -3 -2]]
[[ 1  8  7]
 [ 8 24  5]
 [ 7  7  8]]
[[ -46   89  -57]
 [-135  305 -154]
 [-101   60  -72]]
[[ -46   75  -41]
 [-135  295 -106]
 [-101   44  -58]]
[[ -10  -60   70]
 [-190   30  160]
 [  10  -10    0]]
